### ISSUE TITLE
include conferences and videos 

### ISSUE THREAD

**Issue by gdi2290** [gdi2290/awesome-angular#28]
it would be great to have a list of angular conferences along with their videos

**Comment by rolandjitsu** [comment]
@gdi2290 [#29](https://github.com/angular-class/awesome-angular2/pull/29) probably can close this?

**Comment by gdi2290** [comment]
There is also ng-conf 2015, ng-vegas 2015, and AngularU 2015

**Comment by gdi2290** [comment]
Talks with Angular 2 in them

**Comment by rolandjitsu** [comment]
True, forgot about those :)
